# ifndef _TBCCUST_H_

# define  _TBCCUST_H_
# include "typedefs.h"

typedef struct {
    char CMPY[2];		 /* CHAR(2) */
    char LEDGR[2];		 /* CHAR(2) */
    char ACCT[12];		 /* CHAR(12) */
    char NAME[40];		 /* CHAR(40) */
    char SHORT-NAME[15];	 /* CHAR(15) */
    char STAT-IND;		 /* CHAR(1) */
    char USR-DATA-FLAG;	 	 /* CHAR(1) */
    char DEPT[3];		 /* CHAR(3) */
    char AREA[3];		 /* CHAR(3) */
    char RPSNT[3];		 /* CHAR(3) */
    char CURR[3];		 /* CHAR(3) */
    char TAX-CODE[3];		 /* CHAR(3) */
    char TAX-TYPE[3];		 /* CHAR(3) */
    char TAX-LOCTN[10];		 /* CHAR(10) */
    char TAX-REG-NUM[20];	 /* CHAR(20) */
    char PYMNT-TRM[2];		 /* CHAR(2) */
    char ACCT-CLAS;		 /* CHAR(1) */
    char CR-RATING-FLAG;	 /* CHAR(1) */
    char CR-RATING[3];		 /* CHAR(3) */
    DATE CR-DATE;		 /* DATE */
    char PRIOR-CR-RATING[3;	 /* CHAR(3) */
    DATE PRIOR-CR-DATE;		 /* DATE */
    char CR-CARD-NUM[20];	 /* CHAR(20) */
    char CMPY-REG[20];		 /* CHAR(20) */
    char CATEG[2];		 /* CHAR(2) */
    short PYMNT-BANK-SEQ;	 /* SMALLINT */
    short CLLCT-BANK-SEQ;	 /* SMALLINT */
    char BAL-FWD-IND;		 /* CHAR(1) */
    char CR-INS-FLAG;		 /* CHAR(1) */
    short AUTO-ALLOC-IND;	 /* SMALLINT */
    char CASH-PROMPT-FLAG;	 /* CHAR(1) */
    char BOE-FLAG;		 /* CHAR(1) */
    char TNVR-FLAG;		 /* CHAR(1) */
    char CURR-REVAL-FLAG;	 /* CHAR(1) */
    char AGE-DBT-ENQRY-IND;	 /* CHAR(1) */
    char AGE-DBT-FLAG;		 /* CHAR(1) */
    char STMNT-PRT-IND;		 /* CHAR(1) */
    char STMNT-CURR-IND;	 /* CHAR(1) */
    char STMNT-FREQ-IND;	 /* CHAR(1) */
    char DSCNT-MTHD-IND;	 /* CHAR(1) */
    char DSCNT-TRM[2];		 /* CHAR(2) */
    char IATA-CLRNC-ZONE;	 /* CHAR(1) */
    char IATA-AIRLINE[2];	 /* CHAR(2) */
    char PYMNT-PRCSS-FLAG;	 /* CHAR(1) */
    char DFLT-ALLOC-SEQ-IND;	 /* CHAR(1) */
    char STK-AVLBL-FLAG;	 /* FLAG */
    char CR-LIMIT[];		 /* DECIMAL(13,0) */
    char TEMP-CR-LIMIT[];	 /* DECIMAL(13,0) */
    DATE TEMP-FROM-DATE;	 /* DATE */
    DATE TEMP-TO-DATE;		 /* DATE */
    DATE CR-REVW-DATE;		 /* DATE */
    char CR-REVW-TYPE;		 /* CHAR(1) */
    char CR-STAT;		 /* CHAR(1) */
    char STOP-CR-FLAG[];		 /* CHAR(1) */
    char STOP-CR-DATE[];		 /* DATE */
    char LEGAL-HANDS-FLAG[];		 /* CHAR(1) */
    char LEGAL-HANDS-DATE[];		 /* DATE */
    char TRADE-DSCNT-FLAG[];		 /* CHAR(1) */
    char TRADE-DSCNT-PERC[];		 /* DECIMAL(5,2) */
    char NEXT-STMNT-REF[];		 /* INTEGER */
    char STMNT-ADDR-NUM[];		 /* SMALLINT */
    char DUN-ADDR-NUM[];		 /* SMALLINT */
    char INVCE-PRT-FLAG[];		 /* CHAR(1) */
    char CR-NOTE-PRT-FLAG[];		 /* CHAR(1) */
    char INTRST-FLAG[];		 /* CHAR(1) */
    char CMPND-INTRST-FLAG[];		 /* CHAR(1) */
    char INTRST-RATE-TNAME[];		 /* CHAR(3) */
    char INTRST-DD-GRACE[];		 /* SMALLINT */
    char DUN-SUPPR-FLAG[];		 /* FLAG */
    char DUN-GRP[];		 /* CHAR(3) */
    char DUN-LVL[];		 /* CHAR(1) */
    char SVRTY-MNMM[];		 /* CHAR(1) */
    char SVRTY-MAX[];		 /* CHAR(1) */
    char DUN-LETT-TITLE[];		 /* CHAR(30) */
    char SUPPR-DUN-UNTIL[];		 /* DATE */
    char DUN-RST-VAL[];		 /* DECIMAL(15,2) */
    char DUN-NEXT-SVRTY[];		 /* CHAR(1) */
    char DUN-LAST-SVRTY[];		 /* CHAR(1) */
    char DUN-LAST-DATE[];		 /* DATE */
    char INTER-CMPY-FLAG[];		 /* CHAR(1) */
    char GRP-SUBSID-IND[];		 /* CHAR(1) */
    char GRP-CR-LIMIT[];		 /* DECIMAL(13,0) */
    char HO-BRNCH-IND[];		 /* CHAR(1) */
    char HO-POST-IND[];		 /* CHAR(1) */
    char FLAT-ASSOC-FLAG[];		 /* CHAR(1) */
    char BOE-ASSOC-IND[];		 /* CHAR(1) */
    char SUPP[];		 /* CHAR(12) */
    char ASSOC-BRNCH-IND[];		 /* CHAR(1) */
    char ASSOC-SUBSID-IND[];		 /* CHAR(1) */
    char DFLT-DOC-TYPE[];		 /* CHAR(2) */
    char PRC-TYPE[];		 /* CHAR(3) */
    char SNDRY-ACCT-FLAG[];		 /* CHAR(1) */
    char EDI-REF[];		 /* CHAR(35) */
    char EDI-LOCTN[];		 /* CHAR(13) */
    char EDI-FLAG[];		 /* CHAR(1) */
    char ARCH-DATE[];		 /* DATE */
    char LOCK-FLAG[];		 /* CHAR(1) */
    char LOCK-USR[];		 /* CHAR(8) */
    char LOCK-SESS[];		 /* SMALLINT */
    char DSBLD[];		 /* CHAR(1) */
    char UPDT-DATE[];		 /* DATE */
    char UPDT-TIME[];		 /* TIME */
    char UPDT-USR[];		 /* CHAR(8) */
    char CRTE-DATE[];		 /* DATE */
} TBCCUST_REC;

# endif
